### ISSUE TITLE
Add ability to load image before it gets to view

### ISSUE THREAD

**Issue by cryptiklemur** [callmecavs/layzr.js#1]
Should be able to have an option for load distance, so we can load the image (for example) 200px before it shows up on the page, while scrolling

**Comment by callmecavs** [comment]
definitely going to add this "offset" concept as I think I'll call it.  also planning on emulating the vh unit, so you can offset image load by, say, 25% of the viewport height.  update to come soon

**Comment by cryptiklemur** [comment]
:+1:

**Comment by callmecavs** [comment]
@aequasi: went ahead and added the option - named it threshold, as that's a term that's already been coined by other lazy loading libraries

also updated the docs on the project page to match: http://callmecavs.github.io/layzr.js/#options

**Comment by cryptiklemur** [comment]
awesome!

**Comment by callmecavs** [comment]
@aequasi everything in the docs make sense to ya? want to make sure it's clear that the threshold is interpreted as a percentage of the viewport height - thought this would be more useful than hard px values that don't respond to screen size

**Comment by cryptiklemur** [comment]
Yeah, looks good!

**Comment by callmecavs** [comment]
:+1:
