### ISSUE TITLE
thoughts about my lazyloader?

### ISSUE THREAD

**Issue by vvo** [callmecavs/layzr.js#12]
Did you see https://github.com/vvo/lazyload before building yours?

**Comment by callmecavs** [comment]
nope. not sure the issues section is the best place to call my attention to it though

**Comment by vvo** [comment]
You can have all sort of discussion in the issues of a github project.

It's public, archived, has good context and you can easily link to code!

As you build your lazyr with modern choices like `requestAnimationFrame` I wanted your advice on my more old lazyloader.

Thanks.
