### ISSUE TITLE
Host it onto a CDN

### ISSUE THREAD

**Issue by siamkreative** [callmecavs/layzr.js#19]
As mentioned in the end of the readme, it would be great to have this hosted on a CDN. I suggest both CDNJS and JsDeliver:
- https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library
- https://github.com/jsdelivr/jsdelivr#how-to-submit-or-update-projects

Cheers

**Comment by callmecavs** [comment]
@SiamKreative working on it! will find the time tomorrow to submit to at least 1, and keep you updated.

**Comment by jaxgeller** [comment]
+1

**Comment by irazasyed** [comment]
I sent PRs to both the CDN repos as per their requirements, Waiting for them to merge.

jsdelivr - https://github.com/jsdelivr/jsdelivr/pull/4851
cdnjs - https://github.com/cdnjs/cdnjs/pull/4652

**Comment by callmecavs** [comment]
@irazasyed legend status!! cannot thank you enough - been recently busy recently and haven't been able to get around to this, unfortunately.

will leave this open til they (hopefully) get merged in - thanks for configuring the autoupdate stuff as well.

**Comment by wong2** [comment]
@irazasyed :+1:

**Comment by siamkreative** [comment]
Thanks @irazasyed ! This is the beauty of Open Source.

**Comment by irazasyed** [comment]
@callmecavs No problem, Thanks for the awesome library you've built :)
@SiamKreative Indeed :+1:

@callmecavs The PRs for both the CDNs got merged. I've sent a new PR with CDN instructions added to the README, please review #31. Thanks!
