### ISSUE TITLE
Hidden images are loaded

### ISSUE THREAD

**Issue by siamkreative** [callmecavs/layzr.js#20]
Hey @callmecavs,

It appears that images wrapped in an hidden container will still be loaded. Could you tell me in which context does it make sense? I think most people don't want to be happening, do they?

You can see an example here: http://inquiry.n2clic.com/

![inquiry_n2clic_com](https://cloud.githubusercontent.com/assets/1778633/7466524/f182b278-f30e-11e4-8f73-5d1529e475ce.png)

If what I'm saying does make sense, perhaps you should check if the placeholder image is visible:

``` javascript
//Where el is the DOM element you'd like to test for visibility
function isHidden(el) {
    var style = window.getComputedStyle(el);
    return (style.display === 'none')
}
```

If it doesn't, please lemme know if there's a work around.

Cheers

**Comment by callmecavs** [comment]
@SiamKreative hey man, totally see what you're saying, here are my concerns though:
1. many users are likely lazy loading images _without_ placeholders - how do I account for this use case?
2. what if users are loading as a background image? this check will never be true
3. how do i account for the elements parent being hidden? or the parent's parent being hidden? etc
4. getComputedStyle is slow, and heavy on the browser - running it continually will have a huge performance impact due to constant rendering. is there a better way to check, that addresses all the above?

any thoughts?

**Comment by siamkreative** [comment]
Great thinking. I'm not skilled enough with JavaScript to answer all of your questions haha. It seems to be more complicated than I thought to achieve a visibility check.

I'll do some research to see if other lazy loading scripts implemented this.

**Comment by callmecavs** [comment]
thank you sir, sorry to inundate you with questions haha. would love to hear about your findings - i'll do some research myself this week.

i see you joined me on gitter as well - just registered for that in hopes of increasing community engagement around issues such as this one

**Comment by siamkreative** [comment]
For now I decided to remove the hidden elements from the DOM (as I don't re-use them) instead of hiding them. It works fine.

I checked out a few other scripts (including [echo](https://github.com/toddmotto/echo)), and they all seem to behave the same, which is lazy load anything, even if it's hidden.

**Comment by callmecavs** [comment]
@SiamKreative thought of something that might be the simplest solution to this problem:
- add support for a `data-layzr-ignore` attribute that would prevent Layzr from loading the image, even if it's in the viewport

_Layzr would still continually check the image for its location relative to the viewport, but not load it if that attribute was present_. if you remove the attribute, Layzr will then load it when it comes into the viewport.

if you're working with hidden images, javascript is likely involved anyways - and so removing that attribute from the image likely wouldn't be much of an inconvenience. would appreciate your thoughts on this - happy to add it to the roadmap and can likely implement it today if you think it would suit this type of use case.

**Comment by ErikErkelens** [comment]
I think that would be great - I tried it in my image filtering code. 
In addition, I did have to add a call to _requestScroll() after hiding images to make the few that remained get loaded.

**Comment by callmecavs** [comment]
added this to the roadmap.

Layzr will still check images with the `data-layzr-ignore` attribute but it will never load them, even if they're in the viewport, while they have this attribute.

@ErikErkelens not sure what you mean by the second part - remember that Layzr only checks for images in the viewport _when the user scrolls_ (requestScroll is bound to the window scroll event). even after the data attribute is removed, the user will still need to scroll before Layzr will check and potentially reveal the image. if no scrolling happens, Layzr won't check for images in the viewport. hopefully that explains the issue you encountered

**Comment by ErikErkelens** [comment]
That behavior makes sense. When filtering images, by hiding undesired ones, unloaded images may pop into the viewport. The user resizing the browser window or scrolling will trigger image loading, or the filter code can call _requestScroll() after hiding images.Thanks!

**Comment by callmecavs** [comment]
this has been implemented, just waiting until I have time to do a revamp of the docs before pushing it. coming soon!

**Comment by callmecavs** [comment]
@SiamKreative @ErikErkelens just pushed this! let me know if you runs into any problems

**Comment by ErikErkelens** [comment]
Thanks Michael,

Works great! Hope you fend off other people like me asking for features -
so the library stays nice and small :-)

Erik.

**Comment by dbogod** [comment]
@callmecavs was this actually added? Just tried adding `data-layzr-ignore="true"` to my `img` (also contains `data-src` and `data-srcset` attributes) and nothing changed - all the images were still loaded.
