### ISSUE TITLE
Image dimensions

### ISSUE THREAD

**Issue by MarcusJT** [callmecavs/layzr.js#22]
Neither your demo nor your <img> code example mention whether you can/should specify the height and/or width of images in order to avoid triggering layout changes as the images load. And is there anything to be aware of (in this context) about using retina images?

**Comment by callmecavs** [comment]
@MarcusJT from the [usage section](http://callmecavs.github.io/layzr.js/#usage) of the docs: "Note that images without a placeholder may have no height, or appear broken, before they're loaded." the placeholder, and width/height attributes, are _totally optional_.

i don't recommend using the old school width/height attributes in this nature because they make responsive more difficult - if you need to set a width/height, to preserve layout or otherwise, do so in your CSS - so that you can easily override it. i'd recommend using a combo of width and max-width such that images never overflow their containers.

the bit about retina images depends on your implementation. does that help?

**Comment by MarcusJT** [comment]
I read that bit before I posted the issue because preserving layout is indeed my concern and the documentation is pretty vague about what will happen and how to mitigate the problem. I suggest this is going to be a common query/concern that if left unanswered in the mind of potential users may hamper uptake of your otherwise excellent script, so you should address it explicitly in the documentation.

With regard to retina, your response doesn't really help at all, as I'm interested about the specific implementation that your script provides. To clarify, I suppose what I'm really curious about there is that if I provide a retina image URL via an attribute as per the documentation but don't specify the (max)width or (max)height of the IMG element then surely when your script assigns the retina image URL directly to the SRC attribute (instead of letting the browser automatically seek a "@2x." retina image) it will simply render the image at larger (double) size instead of at the normal size but higher pixel density as one would want for a retina image? Or are you relying on the filename ending @2x and the browser automagically rendering it at the right res for this to work correctly, in which case if the filename doesn't follow this rule (e.g. "frog_retina.jpg" instead of "frog@2x.jpg") then it won't work? Again, these considerations aren't mentioned in your documentation.

**Comment by MarcusJT** [comment]
And what about "@3x." images? ;)

**Comment by callmecavs** [comment]
the `data-layzr-retina` attribute _allows you to load a different image when the [devicePixelRatio](https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio) is greater than 1_ - no more, no less.

whether that image is bigger, and/or has a higher pixel density, is up to the user. the library isn't relying on the browser to "automagically" do anything in regards to hi-res images. to my knowledge, there's currently no cross browser compatible approach for doing so, but i'd be happy to look at any resources you may have found.

this library is only concerned with loading the images - responsibility falls on the user to make sure the proper CSS is in place such that they display correctly. CSS can detect any combination of screen resolutions and what not, and so i'd recommend thoroughly testing your media query setup on different device resolutions if preserving layout is a concern indicative of your implementation.

i'll add a note to the docs regarding width/height attributes, i appreciate the conversation and your insight

**Comment by MarcusJT** [comment]
Ok, thanks for the clarification. The behaviour you state is fine, it's just that none of that was clear from the docs alone so it's important to manage expectations when invoking the magic/scary word "retina". ;)

**Comment by callmecavs** [comment]
anytime man. also, don't forget about the threshold option! using threshold, you can load the images well before they get close to the viewport, which will likely fix any layout problems before the user sees them
