### ISSUE TITLE
Background image usage is not immediately clear

### ISSUE THREAD

**Issue by jgillman** [callmecavs/layzr.js#24]
I get how it's used now, but I had to read through all of the source to figure it out. I like the way it actually works, but it would be nice to have some kind of documentation around that. Or even just a note that `data-layzr-bg` is a boolean, not a source.

First I tried:

``` html
<div data-layzr-bg='/image.jpg' />
or:
<div data-layzr data-layzr-bg='/image.jpg' />
```
# Actual

``` html
<div data-layzr='/image.jpg' data-layzr-bg />
```

**Comment by callmecavs** [comment]
@jgillman been meaning to beef up the usage docs, I'll be sure to include a clarification for this. can definitely see why you'd think it would work as you described.

apologies for the confusion. i figured it was better the second way b/c it allows separate non-retina and retina images, even if loading as a background image.

**Comment by jgillman** [comment]
Yeah! I totally get why it is the way it is, it's better that way. Just wasn't the direction my brain initially assumed :+1:

**Comment by callmecavs** [comment]
going to update the docs this weekend, will close this out once i've done so. thanks for making this clear to me :smiley:

**Comment by callmecavs** [comment]
@jgillman just pushed a huge docs update. they're all on the GitHub README now. let me know if you have any feedback :+1:

**Comment by jgillman** [comment]
Nice, it's very clear now. Also, I think it's good that you don't include any polyfills. It someone really needs it (I do) they should bring their own the the table, so good on ya for not including one!

**Comment by callmecavs** [comment]
@jgillman preciate the input man. yeah, i figured the right route to go was recommending one, but not including one. thanks again!
