### ISSUE TITLE
Load after some waiting without scrolling

### ISSUE THREAD

**Issue by peterbe** [callmecavs/layzr.js#29]
The use case is if you load a page that uses lazyr. The images in your viewport are loaded nicely. You're doing nothing but to just sit and watch the stuff above the fold. 
Then, after some time you decide to scroll down quickly and there's then a big chance that (if you scroll quickly!) that you'll see the placeholder images. The real images could have been loaded in whilst waiting. 

Perhaps this shouldn't be in the core but something I could add in my own code. But then I'd need a way to "trigger" a scroll-down. E.g.

``` html
<script src="layzr.js"></script>
<script>
setTimeout(function() {
    while (!Layzr.atBottom()) Layzr.triggerScrollPage();
} 5 * 1000);
</script>
```

**Comment by callmecavs** [comment]
not sure this has a place in the core, but definitely see the use case.

to achieve something similar, you can probably just bump the threshold up to 200% or 300%, so that when the page loads, you get a couple viewport heights worth of images loading. note that this will effect when images load as the user scrolls though

**Comment by peterbe** [comment]
200% or 300%? What does that equate to as a threshold number?

**Comment by callmecavs** [comment]
100 and 200. basically just drop the % and subtract the original viewport height, which can be thought of as 100 (since the threshold is relative to the viewport height)

**Comment by callmecavs** [comment]
your question actually got me thinking...

perhaps it's better to make the threshold a mixed number, like 1.5? 1.5 would mean "load the image when its the viewport height + half the viewport height away from the top of the window"

any thoughts on that?
