### ISSUE TITLE
commonJS & npm publishing?

### ISSUE THREAD

**Issue by constantx** [callmecavs/layzr.js#3]

**Comment by callmecavs** [comment]
@constantx both are on the roadmap, will keep this open til they've been implemented - thanks!

**Comment by callmecavs** [comment]
@constantx the UMD wrapper is now in place!

**Comment by constantx** [comment]
:beers: rad, will give it a try manually while waiting for npm :)

ps: saved myself 15% load time :)

**Comment by callmecavs** [comment]
@constantx just published to NPM: https://www.npmjs.com/package/layzr.js.  hopefully this will save you some _free_ time :laughing:

gonna close this one out, Bower is still on the roadmap :v:

**Comment by constantx** [comment]
@callmecavs :speedboat:

**Comment by brunowego** [comment]
Take a look at #16
