### ISSUE TITLE
Version number in min.js file

### ISSUE THREAD

**Issue by peterbe** [callmecavs/layzr.js#30]
I have no idea which version I installed last time. All I know is that bower found and downloaded version 1.2.2. 

It would be awesome if the version number could be inserted as a comment on the first line of the `dist/layzr.min.js`. 

[Autocompeter does this](https://github.com/peterbe/autocompeter/blob/master/gulpfile.js#L42) using `gulp-header`.

**Comment by callmecavs** [comment]
going to do some surveying of other prominent JS libs (not to say that mine is prominent haha) and try to follow the industry best practice on this one.

if you have some examples of other libs that include a comment indicating version or otherwise in the minified file, i'd appreciate you linking them. thanks for the gulp plugin recommendation as well

**Comment by peterbe** [comment]
Other libs other than [autocompeter](https://github.com/peterbe/autocompeter/blob/master/gulpfile.js#L42)?
I don't think it matters. Where you get the version number from might vary but that gulpfile is a great example of how you're supposed to get it in there.

**Comment by peterbe** [comment]
Oh, another thing you should consider is to NOT work on a file in the `dist/` directory. That directory is usually meant for computer generated things. 

In Autocompeter I work on the files in `src/` and my gulpfile.js creates the files in `dist/`.

**Comment by callmecavs** [comment]
what i was asking was: do major js libraries include version numbers in their minified versions?  i'd like to follow their lead - based on what i'm seeing, it looks like they do, and so i've added this to the roadmap.

completely see your point about the src folder. an added benefit would be using something like gulp-umd to add the UMD wrapper, to keep that ugliness out of the source file.

both changes coming later today, thanks dude!

**Comment by peterbe** [comment]
Examples:
- [jquery](http://code.jquery.com/jquery-2.1.4.min.js)
- [angularjs](https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js)
- [localforage](https://raw.githubusercontent.com/mozilla/localForage/master/dist/localforage.min.js)

Yeah, I didn't know about gulp-umd but that's a really good point!

**Comment by callmecavs** [comment]
yep, seems to be standard. thanks man, will update you when i make some changes later today

**Comment by callmecavs** [comment]
@peterbe fixed the repo folder structure (added the `src` folder, `dist` folder is only processed output) in the new release, v1.3.0.  part of this fix was adding a comment to the top of both `dist` files that includes version number. thanks again for the help bud, `gulp-header` proved the best way to go about it
