### ISSUE TITLE
Can load with AngularJS

### ISSUE THREAD

**Issue by bukinoshita** [callmecavs/layzr.js#33]
I'm using AngularJS with some routes, but the browser is not recognizing LayzerJS and don't give any error, just don't load :disappointed: 

Do you guys know anything about that?

**Comment by peterbe** [comment]
How are you inserting/invoking layzr?

**Comment by callmecavs** [comment]
@BrunoKinoshita are you creating an instance?

simply loading the script won't make it work - check out [this section](https://github.com/callmecavs/layzr.js#instance-creation) of the docs

**Comment by callmecavs** [comment]
@BrunoKinoshita any word on this in light of the above comments?

**Comment by bukinoshita** [comment]
``` javascript
var layzr = new Layzr({ 
  selector: '.molecule-exploreContent',
  attr: 'data-layzr',
  bgAttr: 'data-layzr-bg'
});
```

**Comment by callmecavs** [comment]
@BrunoKinoshita two of the options in your instance (`attr: 'data-layzr'` and `bgAttr: 'data-layzr-bg'`) are the defaults - so you don't need to include them. the following is equivalent to what you have above:

``` javascript
var layzr = new Layzr({ 
  selector: '.molecule-exploreContent'
});
```

glad this was the fix to your issue.
