### ISSUE TITLE
iOS Chrome 42 bug

### ISSUE THREAD

**Issue by AlbertKogan** [callmecavs/layzr.js#35]
Hi!

Seems to be that in this iOS Chrome build (42.0.2311.47) plugin can't bind a scroll event listener:

``` javascript
this._optionsContainer.addEventListener('scroll', this._requestScroll.bind(this), false); 
```

Layzr v1.1.5 work fine in this browser. Try to compare this verison and current version of plugin (1.4.0) and can't find where is problem.

**Comment by callmecavs** [comment]
@AlbertKogan the demo site has the newest version (1.4.0) on it. tested it on my iphone 6 in Chrome 42, not seeing any bugs. remember that in chrome, the scroll event fires _after momentum scrolling stops_, and so it may appear as though the scroll isn't bound properly but unfortunately the browser just doesn't handle scroll events well.
