### ISSUE TITLE
[bug] requestAnimationFrame error for Capybara

### ISSUE THREAD

**Issue by stephenkerrhs** [callmecavs/layzr.js#36]
Could someone patch the code to ensure requestAnimationFrame exists in the window.

We are using Capybara in our project to test the JavaScript and our tests are failing as the requestAnimationFrame function is undefined.

Thank you in advance.
## 

**Source**
I have sourced the error to come from:

```
Layzr.prototype._requestTick = function() {
  if(!this._ticking) {
    requestAnimationFrame(this.update.bind(this));
    this._ticking = true;
  }
};
```
## 

**Traceback**
Capybara::Poltergeist::JavascriptError:
       One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).

```
   ReferenceError: Can't find variable: requestAnimationFrame
   ReferenceError: Can't find variable: requestAnimationFrame
```

**Comment by stephenkerrhs** [comment]
Old version of phantomjs was the issue.

**Comment by callmecavs** [comment]
thanks for posting the fix, glad you were able to work it out.
