### ISSUE TITLE
better handling of image load callback

### ISSUE THREAD

**Issue by geekyme** [callmecavs/layzr.js#38]
At the moment, there's a brief period of wait while the image is being downloaded and displayed. 

Is it possible to make the callback only run when the image is fully downloaded, so that we can do things like fading in the image pinterest style

**Comment by callmecavs** [comment]
@geekyme you're right, _but_ it's really hard to accurately detect image load - it's inconsistent across even the most modern browsers. there are entire libraries dedicated to it, and so in the interest of size and scope I decided to leave it out.

inside the callback, `this` is a reference to the image node. so if you're using jQuery, or some other library that exposes a `load` event for images, you can bind it directly to the image node, and put your animation/transition inside the callback of that event. does this help?
