### ISSUE TITLE
Handle dynamically created images

### ISSUE THREAD

**Issue by pbcomm** [callmecavs/layzr.js#42]
Looks like there is no way to update the current instance if any dynamically created images were injected into the dom after instantiation.

**Comment by callmecavs** [comment]
just call the [`updateSelector`](https://github.com/callmecavs/layzr.js/blob/master/src/layzr.js#L130-L133) method after you inject your images. you may also want to call the [`update`](https://github.com/callmecavs/layzr.js/blob/master/src/layzr.js#L135-L152) method too, just in case an injected image is in the viewport
