### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by jhil** [callmecavs/layzr.js#43]
Github pages site doesn't have a favicon.

![screen shot 2015-07-10 at 7 55 55 pm](https://cloud.githubusercontent.com/assets/2228347/8632035/eaeeff8a-273d-11e5-9478-e6649ae82fcd.png)

**Comment by jaxgeller** [comment]
+1

**Comment by callmecavs** [comment]
let's try to keep the issues related to the code gentlemen
