### ISSUE TITLE
background image - not centered

### ISSUE THREAD

**Issue by amanjareck** [callmecavs/layzr.js#46]
It's a great plugin, But the document about background image is not clear, also, have no option to set background image as center, fixed, repeat or no-repeat.

**Comment by callmecavs** [comment]
If the element has the data attribute `data-layzr-bg`, then the image will be loaded as a background image.  This attribute can be customized per the options object passed to your instance.

Layzr only sets the `background-image` property - use the other background properties to set the other values you mention above.  Any other questions, just ask.

**Comment by amanjareck** [comment]
Yup! Got it to work! Thanks for the conformation though.. thought I m missing something! :+1: for the plugin
