### ISSUE TITLE
Responsive images support

### ISSUE THREAD

**Issue by zauni** [callmecavs/layzr.js#48]
Hi @callmecavs,
are you planning to support responsive image attributes like srcset/sizes or the picture element? This would be a great addition in responsive websites.

Thanks anyway for the great work you put into layzr.js!

**Comment by callmecavs** [comment]
hey dude - most likely this will appear in v2.0.0.  you can track the progress on the [branch](https://github.com/callmecavs/layzr.js/tree/v1.5.0) if you're interested.  thanks for expressing interest, always happy to hear from users what they need/want

**Comment by pieplu** [comment]
Hi @callmecavs, yes, support picture elements would be great!

Thanks for this work!

**Comment by callmecavs** [comment]
@pieplu :+1:

**Comment by samuelsiau** [comment]
Awesome! Love layzr.js. I already used layzr.js in eight client websites. I can't wait support picture elements.

**Comment by vinkla** [comment]
:+1: for this feature. Do you have any ETA on this? How can we help out?

**Comment by callmecavs** [comment]
@vinkla v2.0.0 is nearing completion - just need to get some time this weekend to test it :boy: :gun:

if youre curious, take a look at the code on the branch, here's a link to the relevant lines for picking the image source: https://github.com/callmecavs/layzr.js/blob/v2.0.0/src/layzr.js#L80-L103

**Comment by vinkla** [comment]
Awesome :+1: Keep up the good work!

**Comment by callmecavs** [comment]
@vinkla edited my previous comment after you responded, I linked the relevant code for ya

**Comment by vinkla** [comment]
Cool, thanks! I'll try this first thing next week. Even if you've pushed the stable version or not.

**Comment by callmecavs** [comment]
:+1: the docs aren't updated, I apologize and wish you the best of luck

**Comment by vinkla** [comment]
No worries, I think I can manage :)

**Comment by vinkla** [comment]
@callmecavs I didn't manage :disappointed: Could you paste an example of how the html tag should look like?

Is this correct?

``` html
<img data-layzr="a1.png 1000w, a2.png 200w">
```

**Comment by callmecavs** [comment]
@vinkla thats the correct syntax. are you getting any console errors?

**Comment by DarioSalutt** [comment]
Hi just wondering if there is any updated documentation or demo RE: how to implement picture element/responsive images etc. Thanks would love to use this feature.

**Comment by vinkla** [comment]
@callmecavs sorry for late answer but I did get errors. It seems it appended the width `200w` to the image url and then it couldn't find the image since the url was broken.

**Comment by callmecavs** [comment]
i've resumed development on v2, and will likely release it before the end of the week. now that [`srcset`](http://caniuse.com/#search=srcset) support has been adopted by webkit browsers, it will most definitely be making an appearance

progress can be found on the branch: https://github.com/callmecavs/layzr.js/tree/v2.0.0

**Comment by vinkla** [comment]
Okay, great news! Keep up the good work.

**Comment by callmecavs** [comment]
coming in v2! due out soon.

**Comment by vinkla** [comment]
:+1:

**Comment by hackuun** [comment]
Is it implemented or not?
