### ISSUE TITLE
CloudFlare Rocket launcher conflict 

### ISSUE THREAD

**Issue by indesignlatam** [callmecavs/layzr.js#49]
Hello,

I just deployed my site where i use CF Rockect Launcher to help speed up the site. But when using Layzr.js images wont load, i think the problem may be on Rockect Launcher that is a beta feature, but i just thougth it will be good to let you know there is an issue with it.

Thanks for the great library by the way.

**Comment by callmecavs** [comment]
hey man, thanks for the kind words.  are there any errors in the console?

also, did you forget to do the [image setup](https://github.com/callmecavs/layzr.js#image-setup)? you have to put your image sources in the `data-layzr` attribute otherwise they wont load.

**Comment by indesignlatam** [comment]
No errros in the console the setup is done, it works ok when disabling Rocket Loader. Dont know how else to debug the problem, rocket loader creates a single file with all js file present something migth go wrong in the process but ive got no clue.

**Comment by callmecavs** [comment]
hmm. my next guess is that the script is firing before the DOM is ready. can you try wrapping the code you use to create your instance inside a DOMContentLoaded or window load event?

**Comment by indesignlatam** [comment]
Im using jquery and im loading the library as follows

``` js
$(function() {
    var layzr = new Layzr();
}
```

This code loads the code on document ready

**Comment by callmecavs** [comment]
is that ready event firing? is it possible that the script is loaded after the event fires so that code is never executed?

**Comment by callmecavs** [comment]
closing this as its specific to your environment, not the lib
