### ISSUE TITLE
Repeating Option?

### ISSUE THREAD

**Issue by zslabs** [callmecavs/layzr.js#50]
While Layzr is normally used for images, I'm attempting to use it as our generic scrollspy implementation, more specifically, lazy loading more items. The first time it hits the select it works fine, but I'd also like to be able to continue to trigger the callback the next time it sees that "load more" trigger. Is there an internal node collection I can continue to remove the item from or is there a better way to approach this? Thanks.

**Comment by callmecavs** [comment]
perhaps try calling [`updateSelector`](https://github.com/callmecavs/layzr.js/blob/master/src/layzr.js#L131-L134) as the new "load more" buttons appear. i'm assuming there are multiple "load more" triggers, and so as the 2nd, 3rd, etc appear they will need to be added to the selectors nodelist.

if there's only 1 "load more" trigger, make sure the `data-layzr` attribute stays on it.  once it enters the viewport, the library will [attempt to remove it](https://github.com/callmecavs/layzr.js/blob/master/src/layzr.js#L124-L128), and thus not fire the callback next time it sees it.

let me know if that ends up working out for you, cool to see people using layzr for more than just images! those would be my best guesses
