### ISSUE TITLE
The image is blank in ajax

### ISSUE THREAD

**Issue by chomyeong** [callmecavs/layzr.js#52]
Hi friend,I have a question.
When I use ajax load data in mobile,but the image invisible on the bottom.

**Comment by callmecavs** [comment]
@chomyeong not sure I understand the problem.  try calling `updateSelector()` on your layzr instance after you load the content in dynamically.

**Comment by chomyeong** [comment]
I‘m sorry,bro. Because my English is weak,so I can't describe my question.But I will try describe my question.So thank you for reply my question!
The question is the image cannot be displayed when I use ajax load data. 
I wish you can understand my question. If you can't understand my question,please click the link:
http://wx.91jinshilin.com/index.php?s=/addon/Education/Index/searchlist.html.
When it scroll to bottom of page the image cannot be display in mobile.
So,I'm very sorry.I hope your reply. Thanks a lot! bro! 
By the way, I cannot understand what does it mean about updateSelector(). It's a function? Jquery?
I'm very sorry!

**Comment by wong2** [comment]
can you give a minimal example to produce the bug?

**Comment by chomyeong** [comment]
@wong2 I'm sorry,bro. It's not a bug,maybe I will not use it. 
If you don't understand my question,you could click the link in above. 
Please select mobile device.
When all data have loaded you will see the question.
