### ISSUE TITLE
v2.0.0

### ISSUE THREAD

**Issue by callmecavs** [callmecavs/layzr.js#53]
Is back under active development! And will likely **release this weekend or early next week**, depending on how long it takes to update the README.

To be included:
- **complete rewrite** - Layzr now uses ES6 syntax, and along with it an upgraded build system
- **`srcset` support** (finally)
- simplified options/configuration (less data attributes on elements required)
- event emitter syntax for binding callbacks
- better handling of dynamically added elements
- ~ 30 less lines of code in the `src` file

check in on the progress on the [v2.0.0 branch](https://github.com/callmecavs/layzr.js/tree/v2.0.0)

as always, your support is appreciated, and my sincerest thanks goes out to everyone that has helped make this library as popular as it is :raised_hands:

**Comment by samuelsiau** [comment]
+1. Excited.

**Comment by callmecavs** [comment]
it has been released!
