### ISSUE TITLE
Simple Demo Needed

### ISSUE THREAD

**Issue by MarkOGDev** [callmecavs/layzr.js#56]
Hello,

Please can you add a simple demo with which we we can easily view the source code of both the HTML and the JS. i.e. just a blank HTML page with a few images and all initilisation JS in the page.

I have created an empty html page with only one image but I can not get the image to load no matter what options I use.

There must be a simple explanation but I have no source code of a working example to compare with.

Regards,
Mark.

**Comment by callmecavs** [comment]
@MarkOGDev per the [Setup Images](https://github.com/callmecavs/layzr.js#setup-images) and [Example Code](https://github.com/callmecavs/layzr.js/blob/master/examples/small.js) sections of the docs, the simplest possible configuration would look as follows:

``` html
<!DOCTYPE html>

<html>
  <head></head>
  <body>
    <!-- setup images, only the data-normal attribute is required -->
    <img data-normal="normal.jpg">

    <!-- optionally include data-retina and data-srcset attributes -->
    <img data-normal="normal.jpg"
         data-retina="retina.jpg"
         data-srcset="small.jpg 320w, medium.jpg 768w, large.jpg 1024w">

    <!-- load Layzr -->
    <script src="layzr.min.js"></script>

    <!-- start up Layzr -->
    <script>
      document.addEventListener('DOMContentLoaded', function(event) {
        instance
          .update()           // track initial elements
          .check()            // check initial elements
          .handlers(true)     // bind scroll and resize handlers
      })
    </script>
  </body>
</html>
```

please don't hesitate to reach out with any more questions!

**Comment by PaulMorel** [comment]
Does v2.0 only work on ES6 environments?

**Comment by callmecavs** [comment]
@PaulMorel nope! the source is transpiled down to ES5 using Babel

exhaustive browser support is listed [on the README](https://github.com/callmecavs/layzr.js#browser-support)

**Comment by PaulMorel** [comment]
~~I can't seem to get Lazyr to work despite following your examples. I can't for the life of me figure out what I'm doing wrong.~~

~~I followed `small.js` example, but I end up getting. `Uncaught ReferenceError: Lazyr is not defined(…)`~~

Well no wonder it doesn't work I've been writing La**zy**r instead of La**yz**r.

**Comment by callmecavs** [comment]
@PaulMorel happens to the best of us :wink: been there a few times myself haha
