### ISSUE TITLE
Missing bower.json file

### ISSUE THREAD

**Issue by andreicek** [callmecavs/layzr.js#57]
When trying to install with `bower install layzrjs an error is returned:

```
bower layzrjs#*           invalid-meta layzrjs is missing "main" entry in bower.json
bower layzrjs#*           invalid-meta layzrjs is missing "ignore" entry in bower.json
```

**Comment by callmecavs** [comment]
@andreicek thanks for opening the issue and pull request, but unfortunately I've dropped Bower support for v2.0.0 and on. I think npm is a better package manager, and is now quite common for managing frontend dependencies.  thanks for the contribution tho!

**Comment by andreicek** [comment]
No problem! :+1:
