### ISSUE TITLE
ASYNC layzr.js

### ISSUE THREAD

**Issue by ericvalois** [callmecavs/layzr.js#60]
Hi,

Do you think it's possible to make layzr.js asynchronous?  

Something like :

```
<script async src="js/layzr.min.js"></script>
<script async src="js/instantiate.js"></script>
```

It's not working for me and I think the error is with the initiation.

``` javascript
document.addEventListener('DOMContentLoaded', event => {
...
});
```

What do you think?

**Comment by callmecavs** [comment]
if you're using the `async` property on the script tag, its likely the script is executing after the `DOMContentLoaded` event has fired - so Layzr never gets initiated.

run a check like this. this will run Layzr if the DOM is ready, or attach an event listener to wait for it to be ready if not:

``` es6
// if the DOM is ready, create Layzr instance
if(document.readyState === 'interactive' || document.readyState === 'complete') {
  // create instance
  const instance = Layzr()

  // ...
}
// otherwise, wait for it to be ready
else {
  document.addEventListener('DOMContentLoaded', event => {
    // create instance
    const instance = Layzr()

    // ...
  })
}
```

**Comment by ericvalois** [comment]
Yes, I use exactly the small exemple and it's not working when both script are ASYNC.

I think `DOMContentLoaded` don't fire a the good time because the script load asynchronous. I tried to concat both (layzr.min.js and the instantiation code) and it's also not working if the script is asynchronous but it work if I remove the async param.

**Comment by callmecavs** [comment]
please use the code in my comment above, with the concatenated file. if you're going to use the `async` property, you cant rely only on the `DOMContentLoaded` event, because it will have likely fired before your script executes

**Comment by ericvalois** [comment]
Thank you,

It's working now with the ASYNC attribute on the script, but it's not working anymore on IE.

You know why? 

```
// if the DOM is ready, create Layzr instance
if(document.readyState === 'interactive' || document.readyState === 'complete') {
  // create instance
  const instance = Layzr({threshold: -10, normal: 'data-normal', srcset: 'data-srcset'});

  instance
    .update()           // track initial elements
    .check()            // check initial elements
    .handlers(true)     // bind scroll and resize handlers
}
// otherwise, wait for it to be ready
else {
  document.addEventListener('DOMContentLoaded', event => {
    // create instance
    const instance = Layzr({threshold: -10, normal: 'data-normal', srcset: 'data-srcset'});

    instance
    .update()           // track initial elements
    .check()            // check initial elements
    .handlers(true)     // bind scroll and resize handlers
  })
}
```

**Comment by callmecavs** [comment]
@ericvalois some of that code (that fat arrow function, as well as the variable declarations) is ES6 - you'll need to transpile it down to ES5 to get it to work in most browsers - using Babel or Traceur.

if youre already transpiling it - are there any errors in the console on load? how about after you scroll the page?

**Comment by ericvalois** [comment]
Only a Syntax error on IE11 and 10 for the following line. It's weird because that line work fine without the conditional statement. I mean, your script work just fine with IE10+, so it must be the new conditional statement.

Syntax error on IE11 onload

```
document.addEventListener('DOMContentLoaded', event => {
```

Thanks for your help, by the way :)

**Comment by callmecavs** [comment]
@ericvalois that problem is the fat arrow: `=>`. that's ES6 syntax, which isn't supported in IE. change it to this and it will working all browsers:

```
document.addEventListener('DOMContentLoaded', function(event) {
```

**Comment by ericvalois** [comment]
@callmecavs you are the man! It's working now!

Thanks a lot!

**Comment by callmecavs** [comment]
@ericvalois no problem, glad i could help :beers:

**Comment by gplusdotgr** [comment]
@callmecavs so essentially the suggestion/recommendation would be to not use it `async` or `defer` right? I guess logically it makes sense as the script has to be executed before DOMContentLoaded? Trying to understand the logic behind this

**Comment by callmecavs** [comment]
@gkatsanos layzr needs to cache elements _after_ the DOM is ready.

`async` and `defer` attributes have a lot to do with where your `script` tags are in your HTML document - so it's hard to make blanket recommendation. that being said though, it should be fine to use `async` and/or `defer` with Layzr.

just make sure all the images you want to lazy load are in the DOM before Layzr runs. `defer` guarantees execution order, whereas `async` doesn't, so depending on your use case (and again where your `script` tags are in the HTML) one or the other might cause trouble.  but assuming a standard HTML document, where all script tags appear right before the closing `body` tag, you should be in the clear to use either/both
