### ISSUE TITLE
Ability to abort `setSource` process in `src:before` event

### ISSUE THREAD

**Issue by dpuscher** [callmecavs/layzr.js#64]
As a developer I would like to be able to abort the `setSource` process in the callback of the `src:before` event to be able to extend the lazy loading to background-images without adding a `src` attribute to an incompatible element (e.g. `div`)

This is how I tried to accomplish it:

```
Application.layzr = Layzr();

Application.layzr.on('src:before', function(element) {
  if (element.tagName.toLowerCase() !== "img") {
    element.style.backgroundImage = "url(" + (element.getAttribute('data-normal')) + ")";
    element.removeAttribute('data-normal');
    return false;
  }
});
```

Even though this works, it will set a `src="null"` attribute to my element which is not very nice.

**Comment by callmecavs** [comment]
using the existing API/events, the best solution imo would be to remove the `src` attribute from the incompatible element in the `src:after` event.

multiple event handlers can be attached to the `src:before` event, and the event emitters `emit` method simply calls a list of functions in sequence. it would be more or less impossible to keep track of the return values of those functions, so I cant see the `return false` approach working.

the difficulty in lazy loading background images is that theres no way to do so using `srcset`. [`image-set`](http://caniuse.com/#search=image-set) will eventually solve this, but is significantly lacking in browser support currently. besides basically reimplementing it in JS, which would significantly bloat the library, there's no great solution for responsive background images currently. will leave this open for now, need to do some thinking on it. I appreciate the feedback

**Comment by callmecavs** [comment]
@dpuscher as I did with `srcset`, I'll likely wait until nearly complete browser support before implementing this feature (using `image-set`).
