### ISSUE TITLE
bgAttr is removed?

### ISSUE THREAD

**Issue by puredazzle** [callmecavs/layzr.js#65]
Hello,

Thanks for great plugin. Just a question, have you removed the support for lazyload background images? Can't find any information about this.

**Comment by callmecavs** [comment]
The attribute has been removed, but it's behavior can be accomplished using the event system new to v2.0.0. See this issue, which explains the rationale behind removing it, and how to achieve the same thing without using the data attribute: https://github.com/callmecavs/layzr.js/issues/54
