### ISSUE TITLE
Hidden images are loaded again in 2.x

### ISSUE THREAD

**Issue by nkpz** [callmecavs/layzr.js#70]
In #20 a solution was implemented for this, but it didn't seem to make it into this version.

See https://github.com/nnjpp/layzr.js/commit/8d4612ab92d767abe0433f87b13261879e0ef129 for a simple enough solution that seems to work. I tend to write for max legibility and minify later, but this could very easily be reduced to a 1 line change.

I can open a PR for that here if you want.

On a side note, package.json pulls in the latest version of some dependencies that don't play well with this configuration. I needed to make these changes to get the build working:

installed `babel-preset-es2015` and `babel-plugin-external-helpers` in package.json for both knot and layzr
modified babelrc for both knot and layzr:
https://github.com/nnjpp/layzr.js/blob/56181287918bbe61f7153ed5438ecef8be367e54/.babelrc
https://github.com/nnjpp/knot.js/blob/36cb1d28b5285d7a15245025ca1745cf2a7c68da/.babelrc

**Comment by callmecavs** [comment]
@nnjpp `hidden` attribute support was removed in the v2.x releases. use the new [events](https://github.com/callmecavs/layzr.js#events) to simulate the functionality.

issues related to importing should be fixed given the updated `dist` files in the latest release. let me know if they're still not working

**Comment by crenshaw-dev** [comment]
Can you provide an example? I see how to attach to the src:before event, but not how to prevent the src attribute from being set.
