### ISSUE TITLE
Nothing happening and 'forEach' error on using instance.check()

### ISSUE THREAD

**Issue by Bram-Zijp** [callmecavs/layzr.js#76]
Installed the plugin through `npm i --save layzr.js`
In my app.js file i include the module like so
```
import Layzr from 'layzr.js'
const lazy = Layzr()
lazy.check()

```

When I added the `lazy.check()` the following error popped up:

```
Uncaught TypeError: Cannot read property 'forEach' of undefined
    at Object.check (eval at ../node_modules/layzr.js/dist/layzr.module.js (bundle.js:761), <anonymous>:186:10)

```
in my index.php I have images like so:

`<img data-normal="test.jpg">`

I'm using Webpack 2.2.0

**Comment by Bram-Zijp** [comment]
Had to do something with my paths of which the views where served

**Comment by OumCc** [comment]
```
const lazy = Layzr()

lazy
    .update()
    .check()
```
in this way?
