### ISSUE TITLE
Must have scrolled in order to see anything load. To lazy?

### ISSUE THREAD

**Issue by Bram-Zijp** [callmecavs/layzr.js#77]
Upon landing on http://callmecavs.com/layzr.js/ you can cleary see the Demo area (4k monitor at 1.5 zoom). Not untill having scrolled this area remains empty.

**Comment by callmecavs** [comment]
@Bram-Zijp per the [basic example](https://github.com/callmecavs/layzr.js/blob/master/examples/small.js#L10), you have to call `check` immediately after instantiating if you want to check for images in the initial viewport

**Comment by callmecavs** [comment]
@Bram-Zijp my apologies, completely misread your question. i thought you were talking about it not working on a site you were implementing on. usually when i see "until having scrolled" i immediately jump to "forgot to call the check method"

the demo site is likely (definitely) using an old version of Layzr. probably from the 1.x branch. by doing what i described above, the v2.x branch fixed this.
