### ISSUE TITLE
Layzr not firing 

### ISSUE THREAD

**Issue by gplusdotgr** [callmecavs/layzr.js#79]
Hello,

I'm a bit confused between the documentation and https://photography.tutsplus.com/tutorials/who-needs-amp-how-to-lazy-load-responsive-images-quick-and-easy-with-layzr--cms-27221 . 

1/ Are image height's required? 

2/ I changed some images src to data-normal (and added width/height attributes to be on the safe side), I changed my instantiation code to be : 

```
/* eslint-disable */
// if the DOM is ready, create Layzr instance
if(document.readyState === 'interactive' || document.readyState === 'complete') {
  // create instance
  const instance = Layzr()
  
  // ...
}
// otherwise, wait for it to be ready
else {
  document.addEventListener('DOMContentLoaded', event => {
    // create instance
    const instance = Layzr()
    
    // ...
  })
}
```
The script is loaded in a bundle (browserify) which is loaded with `defer`

nothing happens.. (no console errors) Here's the HTML.
![image](https://cloud.githubusercontent.com/assets/1768834/25288794/41826a00-26c7-11e7-95e9-46008569a9c3.png)

**Comment by callmecavs** [comment]
@gkatsanos i didn't write the article, so I can't speak to how exactly Layzr should be used with AMP.

but, to answer your questions:

1. image heights are not required (keep in mind though that without the images loaded, the height of your page might be different if they're positioned statically - this is what adding heights addresses)
2. check the [basic example](https://github.com/callmecavs/layzr.js/blob/master/examples/small.js), and make sure you're calling `update`, `check`, and `handlers` after you've instantiated Layzr.

throw some console logs in your `if/else` - make sure the images are in the DOM when Layzr is doing its instantiation work. it's possible the images are being added by other JS after the initial DOM ready event fires - especially if your markup is being injected by a JS view library

**Comment by gplusdotgr** [comment]
So, it appears I was missing 

```
  instance
    .update()           // track initial elements
    .check()            // check initial elements
    .handlers(true);     // bind scroll and resize handlers
```
so, overall what worked:

```
document.addEventListener('DOMContentLoaded', event => {
  // create instance
  const instance = Layzr();
  instance
    .update()           // track initial elements
    .check()            // check initial elements
    .handlers(true);     // bind scroll and resize handlers
  // ...
});
```

Suggestion: could you add the update/check/handlers(true) methods as a "minimal setup" (as well as the note for waiting DOMContentLoaded event - almost everyone is using async or defer to load their scripts nowadays) in the main documentation? As it stands one is left to believe that you only need `  const instance = Layzr();` and things just work..

(of course I can offer a PR!)

Lastly, many thanks for making this! Love the fact it's Module importable and written in ES6..

**Comment by callmecavs** [comment]
@gkatsanos glad that fixed your issue - great point about the documentation.  it's unclear in the instantiation section that there are additional steps required for the library to run.  i'll update it when I get a moment.
