### ISSUE TITLE
Showing images on click

### ISSUE THREAD

**Issue by gplusdotgr** [callmecavs/layzr.js#81]
Assuming we have a set of images which are behind a container that is shown with a click handler (display: none => display: block) , which method of Layzr we should trigger as a callback of the click event handler to show the images immediately?
(use cases : Bootstrap tabs, bootstrap collapse/accordions, carousels)

**Comment by callmecavs** [comment]
@gkatsanos call the `check` method manually using your instance - see [here](https://github.com/callmecavs/layzr.js#check)

**Comment by gplusdotgr** [comment]
great, worked, thanks!
