### ISSUE TITLE
Spinner, loading gif etc

### ISSUE THREAD

**Issue by daybugging** [callmecavs/layzr.js#87]
Hey there,
how would one implement loading animation / effects?
thx!

**Comment by callmecavs** [comment]
Add it to your HTML, style it via CSS.  Using the `src:before` and `src:after` events, show and hide it while the image loads.  You can use the `src:before` hook to bind a `load` event handler if needed. More on events can be found on the [README](https://github.com/callmecavs/layzr.js#events).
