### ISSUE TITLE
Images have to have a height and width

### ISSUE THREAD

**Issue by bmsterling** [callmecavs/layzr.js#9]
This is just a note for other users and I am open for better suggestions.

I am working on a responsive site so by default, all my images are set to `width: 100%` and have no height.  There are situations where you may have a number of images that have not been loaded yet and will have a height of maybe 10px.  This will fake layzr into thinking each of them are inview.  My fix is to either make sure the placeholder image is the same resolution as the images you are going to replace or set a min height and width via css.

**Comment by callmecavs** [comment]
added a note to the docs describing that images w/o placeholders may have no height, or appear broken, before they're loaded
